---
title: "HW_5"
author: "Christopher Duran"
date: "2026-05-09"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#data <- read.csv("C:/Users/chrisdduran/Downloads/data.csv", header=FALSE) 
colnames(data) <- c("x1", "x2", "label")
```

```{r}
# Heuristic Function
run_heuristic <- function(data, learning_rate, epochs) {
  set.seed(42) 
  W <- runif(2, min=-0.5, max=0.5)
  b <- runif(1, min=-0.5, max=0.5)
  
plot(data$x1, data$x2, 
      col=ifelse(data$label==1, "blue", "red"), 
      pch=19, xlim=c(0,1.1), ylim=c(0,1.1),
      main=paste("Heuristic (LR=", learning_rate, ")", sep=""), 
      xlab="x1", ylab="x2")
  
abline(a = -b/W[2], b = -W[1]/W[2], col="red", lwd=2)
  
for (e in 1:epochs) {
  for (i in 1:nrow(data)) {
    x <- c(data$x1[i], data$x2[i])
    y_true <- data$label[i]
      
    z <- sum(W * x) + b
    y_pred <- ifelse(z >= 0, 1, 0)
      
    if (y_pred != y_true) {
      if (y_pred == 0) {
        b <- b + learning_rate
        W <- W + learning_rate * x
      } else {
        b <- b - learning_rate
        W <- W - learning_rate * x
      }
    }
  }
```

```{r}
# Plot
abline(a = -b/W[2], b = -W[1]/W[2], col="forestgreen", lty=2)
}
abline(a = -b/W[2], b = -W[1]/W[2], col="black", lwd=3)
}

```

```{r}
# Gradient Descent Perceptron Function
sigmoid <- function(z) {
  1 / (1 + exp(-z))
}

log_loss <- function(y_true, y_pred) {
  eps <- 1e-15
  y_pred <- pmax(pmin(y_pred, 1 - eps), eps)
  -mean(y_true * log(y_pred) + (1 - y_true) * log(1 - y_pred))
}

run_gradient_descent <- function(data, learning_rate, epochs) {
  set.seed(42)
  W <- runif(2, min=-0.5, max=0.5)
  b <- runif(1, min=-0.5, max=0.5)
  
  error_history <- numeric(epochs)
  
plot(data$x1, data$x2, 
      col=ifelse(data$label==1, "blue", "red"), 
      pch=19, xlim=c(0,1.1), ylim=c(0,1.1),
      main=paste("Grad Descent (LR=", learning_rate, ")", sep=""), 
      xlab="x1", ylab="x2")
  
abline(a = -b/W[2], b = -W[1]/W[2], col="red", lwd=2)
  
for (e in 1:epochs) {
  epoch_preds <- numeric(nrow(data))
    
  for (i in 1:nrow(data)) {
    x <- c(data$x1[i], data$x2[i])
    y_true <- data$label[i]
      
    z <- sum(W * x) + b
    y_hat <- sigmoid(z)
    epoch_preds[i] <- y_hat
    error <- y_true - y_hat
      
    b <- b + learning_rate * error
    W <- W + learning_rate * error * x
  }
    
  error_history[e] <- log_loss(data$label, epoch_preds)
  abline(a = -b/W[2], b = -W[1]/W[2], col="forestgreen", lty=2)
}
```

```{r}
abline(a = -b/W[2], b = -W[1]/W[2], col="black", lwd=3)
  
plot(1:epochs, error_history, type="l", col="blue", lwd=2,
      main=paste("Error Plot (LR=", learning_rate, ")", sep=""), 
      xlab="Number of epochs", ylab="Error")
  
    points(seq(10, epochs, by=10), error_history[seq(10, epochs, by=10)], 
        col="red", pch=19)
}

```

```{r}

# Experimental Part
par(mfrow = c(1, 3)) # 1 row, 3 columns
run_heuristic(data, learning_rate=0.01, epochs=65)
run_heuristic(data, learning_rate=0.1, epochs=65)
run_heuristic(data, learning_rate=1.0, epochs=65)

#  Experiments Part 2
par(mfrow = c(2, 3)) # 2 rows, 3 columns
run_gradient_descent(data, learning_rate=0.01, epochs=100)
run_gradient_descent(data, learning_rate=0.1, epochs=100)
run_gradient_descent(data, learning_rate=1.0, epochs=100)

# Reset plotting layout
par(mfrow = c(1, 1))

```
